###
POST http://localhost:8080/douyin/relation/action
Content-Type: application/x-www-form-urlencoded

token=77;,1657802402&to_user_id=46&action_type=1

###
POST http://localhost:8080/douyin/relation/action
Content-Type: application/x-www-form-urlencoded

token=77;,1657802402&to_user_id=46&action_type=2

<> 2022-07-15T153856.200.json